In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\Rishab Saini\Downloads\admission_data.csv")

In [3]:
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GRE Score          500 non-null    int64  
 1   TOEFL Score        500 non-null    int64  
 2   University Rating  500 non-null    int64  
 3   SOP                500 non-null    float64
 4   LOR                500 non-null    float64
 5   CGPA               500 non-null    float64
 6   Research           500 non-null    int64  
 7   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 31.4 KB


In [5]:
df.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [6]:
df.describe()

GRE Score  TOEFL Score  University Rating         SOP       LOR   \
count  500.000000   500.000000         500.000000  500.000000  500.00000   
mean   316.472000   107.192000           3.114000    3.374000    3.48400   
std     11.295148     6.081868           1.143512    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    308.000000   103.000000           2.000000    2.500000    3.00000   
50%    317.000000   107.000000           3.000000    3.500000    3.50000   
75%    325.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             CGPA    Research  Chance of Admit   
count  500.000000  500.000000         500.00000  
mean     8.576440    0.560000           0.72174  
std      0.604813    0.496884           0.14114  
min      6.800000    0.000000           0.34000  
25%      8.127500    0.000000           0.63000  
50%      8.560000    1.000000           0.72000  
75%      9.040000    1.000000           0.82000  
max      9.920000    1.000000           0.97000

In [7]:
df.duplicated().sum()

0

In [8]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [9]:
y=df[['Chance of Admit ']]

In [10]:
y

Chance of Admit 
0                0.92
1                0.76
2                0.72
3                0.80
4                0.65
..                ...
495              0.87
496              0.96
497              0.93
498              0.73
499              0.84

[500 rows x 1 columns]

In [11]:
x=df.drop(columns=['Chance of Admit '])

In [12]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
arr=scaler.fit_transform(x)
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [16]:
df1=pd.DataFrame(arr)
df1

0         1         2         3         4         5         6
0    1.819238  1.778865  0.775582  1.137360  1.098944  1.776806  0.886405
1    0.667148 -0.031601  0.775582  0.632315  1.098944  0.485859  0.886405
2   -0.041830 -0.525364 -0.099793 -0.377773  0.017306 -0.954043  0.886405
3    0.489904  0.462163 -0.099793  0.127271 -1.064332  0.154847  0.886405
4   -0.219074 -0.689952 -0.975168 -1.387862 -0.523513 -0.606480 -1.128152
..        ...       ...       ...       ...       ...       ...       ...
495  1.376126  0.132987  1.650957  1.137360  0.558125  0.734118  0.886405
496  1.819238  1.614278  1.650957  1.642404  1.639763  2.140919  0.886405
497  1.198882  2.108041  1.650957  1.137360  1.639763  1.627851  0.886405
498 -0.396319 -0.689952  0.775582  0.632315  1.639763 -0.242367 -1.128152
499  0.933015  0.955926  0.775582  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [17]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   1.783684e-15  1.202149e-15 -6.439294e-17  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.346008e+00 -2.500419e+00 -1.850542e+00 -2.397950e+00 -2.686789e+00   
25%   -7.508077e-01 -6.899523e-01 -9.751676e-01 -8.828175e-01 -5.235128e-01   
50%    4.679255e-02 -3.160087e-02 -9.979274e-02  1.272712e-01  1.730621e-02   
75%    7.557706e-01  7.913384e-01  7.755821e-01  6.323155e-01  5.581253e-01   
max    2.085104e+00  2.108041e+00  1.650957e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [18]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [19]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [20]:
arr.shape[1]

7

In [21]:
vif_df=pd.DataFrame()

In [22]:
vif_df['vif']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [23]:
vif_df

vif
0  4.464249
1  3.904213
2  2.621036
3  2.835210
4  2.033555
5  4.777992
6  1.494008

In [24]:
df1.corr()


0         1         2         3         4         5         6
0  1.000000  0.827200  0.635376  0.613498  0.524679  0.825878  0.563398
1  0.827200  1.000000  0.649799  0.644410  0.541563  0.810574  0.467012
2  0.635376  0.649799  1.000000  0.728024  0.608651  0.705254  0.427047
3  0.613498  0.644410  0.728024  1.000000  0.663707  0.712154  0.408116
4  0.524679  0.541563  0.608651  0.663707  1.000000  0.637469  0.372526
5  0.825878  0.810574  0.705254  0.712154  0.637469  1.000000  0.501311
6  0.563398  0.467012  0.427047  0.408116  0.372526  0.501311  1.000000

In [25]:
vif_df['feature']=x.columns
vif_df

vif            feature
0  4.464249          GRE Score
1  3.904213        TOEFL Score
2  2.621036  University Rating
3  2.835210                SOP
4  2.033555               LOR 
5  4.777992               CGPA
6  1.494008           Research

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(arr, y, test_size=0.25, random_state=80)

In [28]:
x_train.shape

(375, 7)

In [29]:
x_test.shape

(125, 7)

In [30]:
y_test.shape

(125, 1)

In [31]:
y_train.shape

(375, 1)

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
lr=LinearRegression()##bulid linear regression model for this data

In [34]:
lr.fit(x_train,y_train)

LinearRegression()

In [35]:
import pickle

In [36]:
pickle.dump(lr,open('admission_lr_model.pickle','wb'))

In [37]:
ls

 Volume in drive C is OS
 Volume Serial Number is 04C2-793D

 Directory of C:\Users\Rishab Saini\python BIT\ML

25-09-2023  11:10    <DIR>          .
20-09-2023  11:31    <DIR>          ..
24-09-2023  21:37    <DIR>          .ipynb_checkpoints
25-09-2023  11:11               600 admission_lr_model.pickle
25-09-2023  11:10            34,093 Advertising DataSet.ipynb
21-09-2023  11:58            52,649 LInear regression_admission prediction.ipynb
               3 File(s)         87,342 bytes
               3 Dir(s)  95,682,162,688 bytes free


In [38]:
lr.predict([[337,118,4,4.5,4.5,9.65,1]])

array([[11.92373257]])

In [39]:
#apply scaleer transform data as it cant take direct data
test1=scaler.transform([[337,118,4,4.5,4.5,9.65,1]])

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [40]:
test1

array([[1.81923762, 1.77886545, 0.77558214, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

In [41]:
lr.predict(test1)

array([[0.95115033]])

In [42]:
test2=scaler.transform([[324,107,4,4.0,4.5,8.87,1]])

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [43]:
lr.predict(test2)

array([[0.8032099]])

In [44]:
model=pickle.load((open('admission_lr_model.pickle','rb')))

In [45]:
model

LinearRegression()

In [46]:
model.predict(test1)

array([[0.95115033]])

In [47]:
##create adjusted r square function
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [48]:
adj_r2(x_test,y_test)

0.8319265766005716

In [49]:
lr.coef_

array([[0.02544655, 0.01569743, 0.00486949, 0.00253552, 0.0150292 ,
        0.0688824 , 0.01185401]])

In [50]:
lr.intercept_

array([0.72085852])

In [61]:
 from sklearn.linear_model import LassoCV,Lasso

In [54]:
##linear regression with lasso
lassocv=LassoCV(cv=10,max_iter=200000,normalize=True)
lassocv.fit(x_train,y_train)

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1571: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.war

LassoCV(cv=10, max_iter=200000, normalize=True)

In [55]:
lassocv.alpha_

6.23591654177006e-06

In [64]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=6.23591654177006e-06)

In [65]:
lasso.score(x_test,y_test)

0.8414115348734595

In [66]:
###CV=Cross_validation


In [67]:
###l2 regularization(Ridge)

In [76]:
from sklearn.linear_model import RidgeCV,Ridge

In [73]:
ridgecv=RidgeCV(alphas=np.random.uniform(0,10,50),cv=10,normalize=True)
ridgecv.fit(x_train,y_train)

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavio

RidgeCV(alphas=array([8.41744112, 6.97816014, 9.79664655, 6.58298706, 2.63747557,
       2.70705573, 2.58520513, 3.02253156, 1.83658783, 2.07566801,
       0.49304142, 2.87874469, 2.30487038, 8.56980313, 5.97989666,
       9.56430223, 1.13357099, 6.82901206, 1.45217628, 3.16481331,
       5.55162098, 0.84444945, 9.52589578, 0.93364195, 1.69437547,
       8.40317645, 0.89918092, 8.45982468, 8.71826243, 5.47844929,
       1.51308972, 2.76307209, 4.12081094, 0.07089639, 9.23476446,
       2.24591176, 0.07075695, 4.04102699, 1.70106166, 7.4517808 ,
       8.32865277, 7.87744641, 3.37133013, 0.91453302, 4.07360272,
       3.52999701, 0.42607125, 0.44018981, 9.71700405, 5.85170063]),
        cv=10, normalize=True)

In [74]:
ridgecv.alpha_

0.07075695323577658

In [80]:
ridge_lr=Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.07075695323577658)

In [81]:
ridge_lr.fit(x_test,y_test)

Ridge(alpha=0.07075695323577658)

In [82]:
ridge_lr.score(x_test,y_test)

0.8464929047321486

In [83]:
###elastic net

In [85]:
from sklearn.linear_model import ElasticNetCV,ElasticNet

In [88]:
elastic=ElasticNetCV(alphas=None,cv=10,normalize=True)
elastic.fit(x_train,y_train)

C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1571: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Rishab Saini\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), ElasticNet())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to original_alpha * np.sqrt(n_samples) if l1_ratio 

ElasticNetCV(cv=10, normalize=True)

In [89]:
elastic.alpha_

5.398758815615924e-05

In [94]:
elastic.l1_ratio_

0.5

In [97]:
elastic_lr=ElasticNet(alpha=elastic.alpha_, l1_ratio=elastic.l1_ratio_)
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=5.398758815615924e-05)

In [99]:
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=5.398758815615924e-05)

In [98]:
elastic_lr.score(x_train,y_train)

0.8129521654595389